development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "https://sheltered-sea-43814.herokuapp.com/faye"
  secret_token: "5fbf3f9e2c0840677e8f0d06676c113ab7b21a8e0ffda0db210b0011f7dcbc75"
  signature_expiration: 3600 # one hour
